# Generated by Django 4.2.1 on 2023-06-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bid_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="auctions.bid",
            ),
        ),
    ]
